---
title: "Florida"
author: "Sophia Freuden"
date: "12/23/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(sf)
library(fs)
library(readxl)
library(plyr)
library(tidyverse)
```

```{r reading in Florida shapefile, include=FALSE, warning=FALSE, echo=FALSE}
fl <- st_read("shape/counties.shp")

# So if you get weird errors (like gdal error 4 or a file corruption error) it probably means your file has been corrupted. Redownload it and also keep it with the other GIS files it came with (.shx, .dbf, etc.)

# Don't be afraid to print fl and see what's inside! It will make your life easier.
```

```{r}
dir_create(path = "clean")
```

```{r, include=FALSE, warning=FALSE, echo=FALSE}
write_rds(fl, path = "clean/fl-map.rds")
```

```{r, include=FALSE, warning=FALSE, echo=FALSE}
vector <- readRDS("clean/fl-map.rds")

vector2 <- vector %>%
  filter(STATE_NAME == "Florida")

vector3 <- vector2 %>%
  arrange(NAME)
```

```{r}
pop <- read_xlsx("clean/projections_2019_asrh_detailed_cl.xlsx")

pop <- pop %>%
  arrange(County) %>%
  filter(Age == "Total") %>%
  select(County, `2020`) %>%
  mutate(POP2020 = `2020`) %>%
  select(County, POP2020) %>%
  slice(1:67)

test <- pop$POP2020

# test <- round_any(test, 1000, f = ceiling)

test2 <- round_any(test, 250000)

# I decided to round up to the next 250000. This distorts

# round_any is a plyr verb; be careful with this package and always load tidyverse again after using it.
```

```{r, include=FALSE}
vector3[["POP2020"]] <- test2

# This adds the 2020 population estimates from my external Excel spreadsheet into the shapefile.

plot <- ggplot() +
  geom_sf(data = vector3, aes(fill = format(POP2020, scientific = FALSE))) +
  labs(
    title = "Estimated 2020 Population of Florida by County",
    fill = "Population",
    caption = "Population rounded to nearest 250,000."
  ) +
  scale_fill_manual(values = c(
    "#F1FAF2",
    "#BBDDBF",
    "#8BBD91",
    "#5F9865",
    "#3A7740",
    "#1F5C25",
    "#0B370F",
    "#031C05"
  )) +
  theme(legend.position = "none") +
  theme_minimal()

# Make sure you add the # at the beginning of each hex color code or it won't look right!

# The colors are horrible if you fill by name, just FYI. Honestly not that helpful to fill by county name. Filling by POP2010 is much more helpful.
```

```{r plotting the static pop graph, fig.align="center"}
plot
```



